### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by tylerschroeder7** [tylerschroeder7/MI-449-SS17-740-css-spacing-and-layout-T7bJIb#1]
@KatieMFritz Can you take a look at this? It's [hosted here](https://schro266-kapm87bvfi5cut7bjib.surge.sh/) and meets the following criteria:

- [x] Demonstrate an understanding of the CSS we've learned so far in the class
- [x] Use Flexbox to create the layout of your page
- [x] Use `margin` and `padding` to create space in and between elements
- [x] Use display `block` and `inline-block` properly
- [x] Have fun and do your best to make it pretty, the result should be something you would show to a future employer

**Comment by KatieMFritz** [comment]
Tyler, this is a nice-looking site! I like how you've kept it simple while still making it look unified.

I notice you're using the same styles on multiple different elements, but listing the styles each time. For example:
```css
#threed {
  max-width: 250px;
  border-style: solid;
  border-color: black;
  border-radius: 25px;
  background-color: #3e4240;
}

#gamedev {
  max-width: 250px;
  border-style: solid;
  border-color: black;
  border-radius: 25px;
  background-color: #3e4240;
}
```
This is not only extra lines of code, which can slow down your site, but it makes it harder to update those elements - you'll have to do it for EVERY `id` instead of just once.

Try using `class`es instead of `id`s so you can style all similar elements with one block of CSS rules. If you aren't sure what I mean, just ask. :grin:
